### ISSUE TITLE
Template review finding: Use a single updateConsentState call when possible 

### ISSUE THREAD

**Issue by philpott** [LoicLemeu/Axeptio-Consent-Mode#2]
https://github.com/LoicLemeu/Axeptio-Consent-Mode/blob/5c88e5fadd0c9e0dfe82301040261ae9744f863e/template.tpl#L51-L62

It's best if you can have a single updateConsentState call vs multiple. This will ensure that any scripts that might be waiting for the update command will be able to execute with all the granted permissions vs possibly being invoked twice (and possibly sending multiple beacons).

**Comment by LoicLemeu** [comment]
Hey,

Thanks for your feedback, however I will not continue this template because of recent updates on Google Analytics and GDPR.
